#!/usr/bin/sh

set -e

###
## CONFIG
###
TORN_TOKEN="<TORN_TOKEN>"
DISCORD_TOKEN="<DISCORD_TOKEN>"
DISCORD_CHANNEL_ID="<DISCORD_CHANNEL_ID>"


CHAIN_TIME_THRESHOLD=105
ALERT_TIME_THRESHOLD=30
###
## END CONFIG
###

TORN_TOKEN="${TORN_TOKEN}" DISCORD_TOKEN="${DISCORD_TOKEN}" DISCORD_CHANNEL_ID="${DISCORD_CHANNEL_ID}" CHAIN_TIME_THRESHOLD="${CHAIN_TIME_THRESHOLD}" ALERT_TIME_THRESHOLD="${ALERT_TIME_THRESHOLD}" ./tc-chainwatcher.py

